services:
    db:
        image: postgres:17
        deploy:
            placement:
                constraints:
                    - "node.labels.db == true"
        container_name: mgn-db
        volumes:
             - db_data:/var/lib/postgresql/data
             -  ./deployment/config/postgres/postgresql.conf:/var/lib/postgresql/postgresql.conf
        ports:
            - "${DB_HOST_PORT:-5438}:5432"
        environment:
            POSTGRES_USER: "${DB_USER:-user}"
            POSTGRES_PASSWORD: "${DB_PASSWORD:-password}"
            POSTGRES_DB: "${DB_DATABASE:-mgn}"
            PGDATA: /var/lib/postgresql/data
        networks:
            - mgn-network
        command: ["postgres", "-c", "config_file=/var/lib/postgresql/postgresql.conf"]

    nginx:
        image: nginx:alpine
        container_name: mgn-nginx
        tty: true
        ports:
            - "${NGINX_PORT:-7777}:80"
        volumes:
            - ./deployment/config/nginx/default.conf:/etc/nginx/conf.d/default.conf
            - .:/var/www/mgn
        depends_on:
            - laravel
        networks:
            - mgn-network

    redis:
        image: redis:7-alpine
        container_name: mgn-redis
        deploy:
            placement:
                constraints:
                    - "node.labels.db == true"
        volumes:
            - redisdata:/data
        ports:
            - "${REDIS_HOST_PORT:-6378}:6379"
        networks:
            - mgn-network

    laravel:
        build:
            context: .
            dockerfile: deployment/docker/Dockerfile.php
            target: api
            args:
                - user=radian
                - uid=1000
        container_name: mgn-app
        working_dir: /var/www/mgn
        volumes:
            - ./storage:/var/www/mgn/storage:rw
            - ./bootstrap/cache:/var/www/mgn/bootstrap/cache
            - ./public:/var/www/mgn/public:rw
            - ./.env:/var/www/mgn/.env
            - ./deploy/logs:/var/log:rw
        tty: true
        ports:
            - "${LARAVEL_PORT:-9001}:80"
        networks:
            - mgn-network

        depends_on:
            - db
            - redis

    horizon:
        build:
            context: .
            dockerfile: deployment/docker/Dockerfile.php
            target: worker
            args:
                - user=radian
                - uid=1000
        container_name: mgn-horizon
        working_dir: /var/www/mgn
        volumes:
            - ./storage:/var/www/mgn/storage:rw
            - ./bootstrap/cache:/var/www/mgn/bootstrap/cache
            - ./public:/var/www/mgn/public:rw
            - ./.env:/var/www/mgn/.env
            - ./deploy/logs:/var/log:rw
        tty: true
        networks:
            - mgn-network
        depends_on:
            - db
            - redis

volumes:
    db_data:
        driver: local
    redisdata:
        driver: local

networks:
    mgn-network:
        driver: bridge
