[supervisord]
nodaemon=true
logfile=/var/log/supervisor/supervisord.log
pidfile=/var/run/supervisor.pid

[supervisorctl]
serverurl=unix:///var/run/supervisor.sock
username=admin
password=admin

[program:php-fpm]
command=php-fpm
autostart=true
autorestart=true
stderr_logfile=/var/log/supervisor/php-fpm.err.log
stdout_logfile=/var/log/supervisor/php-fpm.out.log

[program:laravel-worker-normal]
process_name=%(program_name)s_%(process_num)02d
command=php /var/www/mgn/artisan queue:work --queue=normal --sleep=3 --tries=3 --max-time=3600
autostart=true
autorestart=true
stopasgroup=true
killasgroup=true
user=radian
numprocs=2 ; Number of worker processes
redirect_stderr=true
stdout_logfile=/var/www/mgn/storage/logs/worker-normal.log

[program:laravel-worker-summary]
process_name=%(program_name)s_%(process_num)02d
command=php /var/www/mgn/artisan queue:work --queue=summary --sleep=3 --tries=3 --max-time=3600
autostart=true
autorestart=true
stopasgroup=true
killasgroup=true
user=radian
numprocs=1
redirect_stderr=true
stdout_logfile=/var/www/mgn/storage/logs/worker-default.log
