name: Development Workflow

on:
  push:
    branches:
      - development

jobs:
  # Job 1: Build and Test
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      # Checkout the code
      - name: Checkout code
        uses: actions/checkout@v2

      # Set up PHP environment
      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2' # or your Laravel PHP version

      # Install dependencies
      - name: Install Composer dependencies
        run: composer install --no-interaction --prefer-dist --optimize-autoloader

      # Set up testing environment
      - name: Create .env.testing file
        run: |
          cp .env.example .env.testing
          echo "DB_CONNECTION=sqlite" >> .env.testing
          echo "DB_DATABASE=:memory:" >> .env.testing
          php artisan key:generate --env=testing

      - name: Run Laravel Pint (fix)
        run:  ./vendor/bin/pint --test --parallel
      
      - name: Commit Pint fixes
        run: |
          if [ -n "$(git status --porcelain)" ]; then
            git config --global user.email "github-actions@github.com"
            git config --global user.name "GitHub Actions"
            git add .
            git commit -m "chore: fix Pint code style [ci skip]"
            git push origin HEAD:${GITHUB_REF#refs/heads/}
          fi

      - name: Run migrations for testing
        run: php artisan migrate --env=testing --force

      # Run tests
      - name: Run Pest Unit tests
        run: ./vendor/bin/pest --parallel --group=unit

      - name: Run Pest Features tests
        run: ./vendor/bin/pest --parallel --group=feature

      - name: Run Stress tests
        run: ./vendor/bin/pest --parallel --group=stress-test

  # Job 2: Static Analysis
  static-analysis:
    runs-on: ubuntu-latest
    steps:
      # Checkout the code
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Composer dependencies
        run: composer install --no-interaction --prefer-dist --optimize-autoloader

      - name: Verify phpstan installation
        run: ls -l ./vendor/bin

      - name: PhpStan analysis
        run: ./vendor/bin/phpstan analyse --memory-limit=512M
